### ISSUE TITLE
Move "org.lemsml.model" repos

### ISSUE THREAD

**Issue by pgleeson** [NeuroML/NeuroML2#100]
For https://github.com/LEMS:
- [x]  https://github.com/borismarin/expr-parser
- [x]  https://github.com/borismarin/org.lemsml.model (@tarelli moved his to https://github.com/LEMS/org.lemsml.model)
- [x]  https://github.com/borismarin/lems-domogen-maven-plugin (?)
- [ ]  https://github.com/borismarin/domoTest (?)    

For https://github.com/NeuroML:
- https://github.com/borismarin/neuroml2model (rename?)

@borismarin more required?

**Comment by pgleeson** [comment]
These repos are currently being tested/updated here (work in progress):
https://github.com/pgleeson/expr-parser
https://github.com/pgleeson/neuroml2model

**Comment by pgleeson** [comment]
These have been moved to:

https://github.com/LEMS/expr-parser
https://github.com/LEMS/lems-domogen-maven-plugin
https://github.com/LEMS/org.lemsml.model
https://github.com/NeuroML/neuroml2model

@borismarin, ok if go ahead and merge the PRs on these repos?

**Comment by borismarin** [comment]
tá!

2017-06-13 9:00 GMT-03:00 Padraig Gleeson <notifications@github.com>:

**Comment by pgleeson** [comment]
All moved and all tests passing.
