### ISSUE TITLE
Create C++ API for NeuroML 2

### ISSUE THREAD

**Issue by pgleeson** [NeuroML/NeuroML2#102]
## C++ API for reading/editing/writing NeuroML2

Priorities will be:
 - Ease of (re)generation from [latest Schema](https://github.com/NeuroML/NeuroML2/tree/development/Schemas/NeuroML2)
- Ease of installation
- Lack of external dependencies 
- Examples (based on https://github.com/NeuralEnsemble/libNeuroML/tree/master/neuroml/examples)

An initial version of this be worked on by @jonc125 under https://github.com/NeuroML/NeuroML_API

One option to be explored is a quick C++ API with [Codesynthesis XSD](http://www.codesynthesis.com/products/xsd/)...

**Comment by jonc125** [comment]
Note that with CodeSynthesis we can distribute the required bits of their code with the NeuroML API under an open source licence provided that our code "does something useful" rather than just being a wrapper around the auto-generated code. See http://www.codesynthesis.com/projects/xsd/FLOSSE for details. So we'd probably need some utility stuff similar to the Python libNeuroML before we could do this. But if we can then I think the only external dependency would be [Xerces-C++](http://xerces.apache.org/xerces-c/) which is pretty standard.

(People wanting to regenerate the bindings would need to install CodeSynthesis XSD themselves.)

**Comment by jonc125** [comment]
Initial demo created in https://github.com/NeuroML/NeuroML_API/commit/7ce61dbb198d50deb963a6120e28c02c3ba31e14

Some questions:
* Do we want type and method names to match the Schema or Python API?
* I'm guessing we're not worrying about HDF5 import/export for non-Python bindings (at least not yet)?
* Apart from that, I assume that the methods defined in `neuroml/nml/helper_methods.py` would be useful to have in the C++ classes too. (Using http://wiki.codesynthesis.com/Tree/Customization_guide)
* What other extra utility functionality would be wanted in this API?
* What kind of installation experience is wanted? For instance, do we want to make it easy for people using CMake to pick this up as a library?

**Comment by jonc125** [comment]
Done some work on adding custom methods; latest in NeuroML/NeuroML_API@c170898. I haven't done everything from the Python library as some of them appear to be for classes that are now deprecated, and I couldn't see test files using them in the Python repo.

The next step would probably be to package this as a CMake project that can be installed as library + headers, with the hooks for other CMake projects to find it easily.

It could also do with some more thorough testing, including of creating models from scratch. We should agree on a naming convention to follow before doing much more coding around the APi though!

**Comment by pgleeson** [comment]
@jonc125 See above for answers... I have it successfully installed locally and have managed to write another example for creating nml files, but just saw some refactoring for cmake before I could commit.. Let me know when updated version is stable.

**Comment by jonc125** [comment]
@pgleeson Everything should be in the right place now and ready to use. Just some fine-tuning of options, but that shouldn't prevent you adding another example. Would be useful to see what you've done in creating something from scratch to see what kinds of helpers would be wanted there.

Another question - do you have a preference for licence to use? I think we discussed MIT last week? Then I can add the appropriate "Copyright UCL" notices.

**Comment by pgleeson** [comment]
Closing this issue and new ones can be create for refinements.

**Comment by jonc125** [comment]
Probably best to put any new issues in https://github.com/NeuroML/NeuroML_API/issues
