### ISSUE TITLE
Shorthand (JSON?) notation for network specification/generation

### ISSUE THREAD

**Issue by pgleeson** [NeuroML/NeuroML2#106]
As discussed during the 2016 NeuroML editors meeting there is some overlap between the format used for NetPyNE to create cells/populations/connections and that used in MOOSE (Rdesigneur). We should investigate whether it would be possible/useful to have a common format for these, which would also be supported natively by NeuroML libraries. 

An end goal for this would be to have complex connectivity information like this for the Traub et al 2005 model expressible in such a shorthand notation (not verbosely in XML, or procedurally in Python), which can be read and edited by hand, but is standardised.

**Comment by apdavison** [comment]
Here is a presentation from Sergey Gratiy at the Allen Institute on their model representation approach, which also uses JSON: http://neuralensemble.org/media/slides/Sergey_Gratiy_bionet_representation.pdf

**Comment by pgleeson** [comment]
See progress at https://github.com/NeuroML/NetworkShorthand

**Comment by pgleeson** [comment]
Closing this as it's well under way at https://github.com/NeuroML/NeuroMLlite
