### ISSUE TITLE
neuroml wheel

### ISSUE THREAD

**Issue by dilawar** [NeuroML/NeuroML2#108]
python `wheels` are great for distributing packages (https://packaging.python.org/discussions/wheel-vs-egg/). Installing wheel does not require local compilation of package. 

Recently we created wheels for `moose` by following this https://github.com/kozo2/python-libsbml-manylinux .

**Comment by pgleeson** [comment]
Thanks for this @dilawar. We mainly recommend installing libNeuroML and pyNeuroML via pip, using source distributions rather than binaries, and there is no compilation of C++ code etc. required. Is there any advantage to generating/distributing wheels over a source release on pypi?

**Comment by dilawar** [comment]
I see, I thought the XML support is compiled during installation. I can't see any major benefit of wheel in this case.

**Comment by pgleeson** [comment]
Ok, thanks for checking though.

**Comment by rgerkin** [comment]
@pgleeson A conda recipe for NeuroML stuff would be good though
