### ISSUE TITLE
All-to-all projections?

### ISSUE THREAD

**Issue by frothga** [NeuroML/NeuroML2#110]
The example NML2_FullNeuroML has a projection element with no connections specified. In the case of this example, the comment makes it clear that "further elements need to be added". However, it raises a more general question. Should an empty projection element be interpreted as no connections (connections must always be explicit) or all-to-all? An empty projection could imply that all possible connections between two populations exist.

**Comment by pgleeson** [comment]
An empty projection should simply be interpreted as no connections.

**Comment by pgleeson** [comment]
Empty projection in NeuroML2 should certainly contain no connections. This will be possible to specify in NeuroMLlite though: https://github.com/NeuroML/NeuroMLlite/issues/6
