### ISSUE TITLE
`hash` is not available for many nml objects under python3

### ISSUE THREAD

**Issue by dilawar** [NeuroML/NeuroML2#116]
Here is an example:

```
Python 3.7.0 (default, Jul 15 2018, 10:44:58) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import neuroml as nml
In [2]: a = nml.nml.nml.IonChannel( )
In [6]: d = { a : 1 }
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-1f835b414d1a> in <module>()
----> 1 d = { a : 1 }

TypeError: unhashable type: 'IonChannel'
```
Above works fine with python2.

```
>>> import neuroml as nml
>>> a = nml.nml.nml.IonChannel( )
>>> { a : 1}
{<neuroml.nml.nml.IonChannel object at 0x7fdc17172750>: 1}
>>> 
```

This is going to break `NML2` support in moose simulator with python3.

**Comment by rgerkin** [comment]
I can't reproduce this in python 3.5.2, libneuroml module version 0.2.39.  What is your libneuroml module version, @dilawar (i.e. what do you get from `nml.__version__` in the console)?  It could also be change in hashing in python 3.6 or 3.7.

**Comment by dilawar** [comment]
libneuroml version = 0.2.43. 

I could reproduce with python3.5.2 (virtuon Ubuntu-18.04 machine.

**Comment by pgleeson** [comment]
Have reproduced this. There should be no reason to use the object (Cel/IonChannel etc.) as the key in the reader.py code (the root of the problem). I've tested using the id instead here: https://github.com/pgleeson/moose-core/commit/29e089aa950c0cf9d277edaadd77eb9e4d301538 and it seems to work. I'll test this with the latest Moose master code and open a pull request...

**Comment by dilawar** [comment]
Thanks. This should do.

Since this was working with python2.7, I assumed this would work with
python3 as well. 

May be `hash()` can be mapped to `id` of NML object to have consistent
pytho2/python3 behaviour? 



--

**Comment by dilawar** [comment]
Now using the object's id rather than object itself in a dictionary. This fixed the issue.

**Comment by dilawar** [comment]
I've pulled in changes from https://github.com/pgleeson/moose-core/commit/29e089aa950c0cf9d277edaadd77eb9e4d301538 . Seems to works fine after couple of fixes.

**Comment by pgleeson** [comment]
Thanks @dilawar. I'd been making some changes there in the last few weeks but not had the chance yet to open a PR. I'll merge your master and make sure all of my updates are present.

**Comment by rgerkin** [comment]
@dilawar Be careful.  `id` is an identifier for the object's location in memory, whereas the `hash` is on the object contents itself.  For example, an object and it's copy will have the same hash but different id, whereas an updated unhashable object (like a dict) will keep the same id but have a different serialized hash.  For example:
```
import json, copy
x = {'a': 1, 'b': 2, 'c': 3}
print(id(x), hash(json.dumps(x)))
x['d'] = 4
print(id(x), hash(json.dumps(x)))
y = copy.deepcopy(x)
print(id(y), hash(json.dumps(y)))
```

**Comment by dilawar** [comment]
@rgerkin Thanks. I relooked at the code. `a.id` is not `id(a)`. NML's object `id` attribute is unique.  From the schema:

```
    <xs:simpleType name="NmlId">
        <xs:annotation>
            <xs:documentation>An id attribute for elements which need to be identified uniquely (normally just within their parent element).</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z_][a-zA-Z0-9_]*"/>
        </xs:restriction>
    </xs:simpleType>
``` 

```
In [4]: a = nml.IonChannel(id='123')                                                                                           
In [6]: a.id                                                                                                                   
Out[6]: '123'
```
On the other hand, neuroml2 objects are allowed empty id. 

```
>>> import neuroml as nml
>>> a = nml.IonChannel()
>>> a.id
>>>
>>>  {a.id : a }
>>>  {None: <neuroml.nml.nml.IonChannel object at 0x7fb4cdc4f7f0>}
```

As long as `id` is unique and not empty, I think it should be fine. I'll add some checks on the attribute `id`.
