### ISSUE TITLE
NeuroMLCoreDimensions.html: Conversion factors for degC and K are wrong

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/NeuroML2#136]
These are special cases and I think we'll need to handle them separately.

![neuroml-docs-degc](https://user-images.githubusercontent.com/102575/107946293-b9e59b80-6f88-11eb-84b0-587655648b0d.png)
![neuroml-docs-kelvin](https://user-images.githubusercontent.com/102575/107946298-ba7e3200-6f88-11eb-8572-df0d5f95d63f.png)

**Comment by pgleeson** [comment]
@sanjayankur31 This is fixed in the old generate.py here: https://github.com/NeuroML/NeuroML2/commit/8cca851176a336836df819b0c526bdd4875d1857#diff-e415f6551f754d48d311fb2318014ba444563c797a5a3dd865a7cc916e99959a

**Comment by sanjayankur31** [comment]
I thought I'd incorporated this already, but I see that while degC looks OK, K doesn't:

- https://docs.neuroml.org/Userdocs/Schemas/NeuroMLCoreDimensions.html#degc
- https://docs.neuroml.org/Userdocs/Schemas/NeuroMLCoreDimensions.html#schema-units-k

I'll double-check this. Closing here, filed an issue in docs.
