### ISSUE TITLE
Links to bioportal references lead to "page not found"

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/NeuroML2#138]
For example, the button on the [Synapses](https://www.neuroml.org/NeuroML2CoreTypes/Synapses.html) page links to this: http://bioportal.bioontology.org/ontologies/46856/?p=terms&conceptid=cno:cno_0000009, but clicking it goes to a page that says "The page you are looking for wasn't found. Please try again.".

The link in the schema file doesn't work, so this is not specific to the generated HTML.

**Comment by pgleeson** [comment]
Links can be updated to use this form:
https://bioportal.bioontology.org/ontologies/CNO/?p=classes&conceptid=cno_0000009

**Comment by pgleeson** [comment]
Fixed in development. Has it been incorporated into the new documentation?

**Comment by sanjayankur31** [comment]
No, not yet. Filed an issue in the docs repo.
