### ISSUE TITLE
Document Simulation.xml

### ISSUE THREAD

**Issue by cengique** [NeuroML/NeuroML2#169]
Under `Line`, it should indicate whether `scale` is dividing or multiplying (in this case it looks like it's dividing).

**Comment by pgleeson** [comment]
Thanks @cengique. Finally gotten round to adding more documentation on the elements in Simulation, see https://docs.neuroml.org/Userdocs/Schemas/Simulation.html#schema-line. Also added general info on using the LEMS Simulation file: https://docs.neuroml.org/Userdocs/LEMSSimulation.html
