### ISSUE TITLE
[Question] Scoping rules in NML2

### ISSUE THREAD

**Issue by thorstenhater** [NeuroML/NeuroML2#178]
While trying to build my own NML2 support, I have a question about scoping and access rules. 

My current understanding is the following:
- `Parameters` and `Variables` in the current object hierarchy can be read freely, without going through an `Exposure`
  - This include items in the current object and those inherited from its base classes
- Accessing `Variables` in contained objects, ie `Child` and `Children`, can be accessed using `select=child/var` and `select=children[*]/var`
  - `Parameters` cannot be read directly, but must go through a dummy `DerivedVariable `
  - Additionally we need an `Exposure` for the item in question
- Accessing items from enclosing scopes seems likewise possible
  - Example: Reading `v` in `HHRates`
  -  An `Exposure` is needed

**Q** Is this correct so far?

```xml
<?xml version="1.0" encoding="utf-8"?>
<Lems xmlns="http://www.neuroml.org/lems/0.7.6"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.neuroml.org/lems/0.7.6 ../../LEMS/Schemas/LEMS/LEMS_v0.7.6.xsd"
      description="Test Scoping rules">

  <ComponentType name="base">
    <Parameter name="p_base" dimension="none"/>

    <Exposure name="e_p_base" dimension="none"/>

    <Child name="in0" type="inner"/>

    <Dynamics>
      <!-- Setting derived vars from literals -->
      <DerivedVariable name="d_base" value="42"/>
      <!-- Setting derived vars from parameters -->
      <DerivedVariable name="d_p_base" value="p_base" exposure="e_p_base"/>
      <!-- TODO Setting derived vars from child parameters -->
      <!-- Fun fact: using pylems and 'in' implodes, since using `x.in` is a syntax error -->
      <DerivedVariable name="d_p_base" select="in0/e_dd_inner" dimension="none"/>
    </Dynamics>
  </ComponentType>

  <ComponentType name="inner">
    <!-- <Requirement name="e_p_base" dimension="none"/> -->
    <Exposure name="e_dd_inner" dimension="none"/>

    <Dynamics>
      <!-- Setting derived vars from literals -->
      <DerivedVariable name="d_inner" value="42"/>
      <!-- Setting derived vars from others-->
      <DerivedVariable name="dd_inner" value="2*d_inner" exposure="e_dd_inner"/>

      <!-- TODO Getting variables from outer scope -->
      <DerivedVariable name="dp_base" value="e_p_base"/>
    </Dynamics>
  </ComponentType>

  <!-- We need this in order to get _something_ out of (j|py)lems -->
  <Target component="my0"/>

  <base id="my0" p_base="23">
    <in0 type="inner"/>
  </base>
</Lems>
```

Further Questions:
- What happens if multiple items in a nested object expose the same variable name?
  - I would assume names farther out are shadowed.
- Do `Requirement`s change access control?

Unfortunately I cannot really test these assumptions, as jNML is broken on current java 
versions, see #177.

**Comment by pgleeson** [comment]
@thorstenhater Thanks for the question, you're generally correct, and I'm looking into this, but it's related to a few other issues (and I do want to get jnml working mon more recent java versions). I'll get back to you soon about this.

**Comment by pgleeson** [comment]
@thorstenhater Apologies, still working on resolving the java version issues.

I've added an updated version of your script to: https://github.com/OpenSourceBrain/ArborShowcase/blob/main/NeuroML2/tests/Scoping.xml, and added you to that repository. There are tests there for running this script in jnml, so if you wanted to alter that in a branch and commit, it should test the validity of it.

Some points I noticed when testing this:

1) Access from outside for plotting/saving variables is less dependent on exposure/requirements, you can record all variables even if they're not exposed. This is probably a design decision to aid debugging
2) Exposure/requirements are mainly for ensuring access around the model hierarchy, a child says that it requires access to a variable on a parent and that parent neds to expose that value.
3) It **seems like** there is a restriction that you can't change the name of a variable by exposing it with a different name, e.g. you can't expose variable a with name b. This may be a design decision by Robert Cannon, and it seems all the NML libraries stick to this convention. What can be done though is a base type can say "anything which extends me needs to expose something called i", and extending types can choose to make that a DerivedVariable or a StateVariable.
4) The issue of scoping shouldn't come up, as an extending type should either say "I require a variable called v" or "I define a (derived/state)variable called v". It shouldn't do both and in the case that it does the requirement statement is redundant.

**Comment by pgleeson** [comment]
FYI @thorstenhater, issue with compiling for latets java versions should be fixed now. Tests on Java 16 & 17, as well as on Linux, Mac and win have been added for full jnml stack, e.g. here: https://github.com/NeuroML/jNeuroML/actions/runs/1499130290

**Comment by thorstenhater** [comment]
Thank you very much for taking the time and explaining this.
