### ISSUE TITLE
Check status of fractional gate 

### ISSUE THREAD

**Issue by pgleeson** [NeuroML/NeuroML2#186]
@borismarin previously added an example of a channel with fractional gates here: https://github.com/NeuroML/NeuroML2/blob/master/LEMSexamples/LEMS_NML2_Ex24_FractionalConductance.xml, which was presumably required for converting this channel to NeuroML: https://github.com/OpenSourceBrain/korngreen-pyramidal/blob/79a2354c377bd405bc3467ee5bf700c4dd15b73a/NEURON/kslow.mod#L99-L103

Need to check on the status of this and whether the NeuroML form can be converted successfully back to NEURON mod file... Any idea @borismarin?

Will be needed for the conversion of this: https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell/blob/master/NEURON/channels/kslow.mod to NML. 
@shayan823

**Comment by borismarin** [comment]
I would need to have a detailed look at NeuronWriter (in org.neuroml.export, supposing it is still there) to be sure, but I assume that constructs that have been "promoted" to LEMSExamples have been thoroughly tested (shame on me if that is not the case). Anyways, I seem to have asked similar questions some time ago: https://github.com/OpenSourceBrain/korngreen-pyramidal/issues/2

**Comment by borismarin** [comment]
Notice that the kslow channel (as well as all the other ones that model) have been converted to NeuroML2, on the nml2 branch:
https://github.com/OpenSourceBrain/korngreen-pyramidal/blob/nml2/NeuroML2/kslow.channel.nml

**Comment by borismarin** [comment]
more archaeology: 
https://github.com/NeuroML/NeuroML2/pull/86
https://github.com/SilverLabUCL/osbpaper/issues/9#issuecomment-195469658

**Comment by pgleeson** [comment]
Closing as there is a working example running on jnml & jnml_nrn in the repo
