### ISSUE TITLE
Convertion of nml1.8 to nml2

### ISSUE THREAD

**Issue by dilawar** [NeuroML/NeuroML2#25]
Hi,

I am supporting NML version 2 in my Python application. Is there an application which converts models in NML1.8 to version 2?

**Comment by pgleeson** [comment]
Ok to close this @dilawar? I'm not sure the conversion of NML1 to NML2 will go beyond the options above of 1) import to neuroConstruct and export to NML2; and 2) use of the ChannelMLConvert XSL files above (used in nC),
