### ISSUE TITLE
Add gap junction & graded synapse support to NeuroML2

### ISSUE THREAD

**Issue by pgleeson** [NeuroML/NeuroML2#34]
Highly dependent on support for this in jLEMS, see https://github.com/LEMS/jLEMS/issues/31

**Comment by slarson** [comment]
How's this going?  Can @aribrich or I help on this?

**Comment by pgleeson** [comment]
Gap junctions are currently stable and implemented in NML2 & the mapping to NEURON is complete (and they are used in [c302](https://github.com/openworm/CElegansNeuroML/blob/master/CElegans/pythonScripts/c302/examples/c302_B_Syns.nml))

Initial version of analog synapses implemented here: https://github.com/NeuroML/NeuroML2/blob/development/examples/NML2_AnalogSynapses.nml. Needs more testing but initial version working and mapping to NEURON should be straightforward...

**Comment by pgleeson** [comment]
Done in v2beta4.
