### ISSUE TITLE
Add conductance scaling to schema

### ISSUE THREAD

**Issue by borismarin** [NeuroML/NeuroML2#55]
see 
https://github.com/NeuroML/NeuroML2/blob/development/NeuroML2CoreTypes/Channels.xml#L480
https://github.com/NeuroML/NeuroML2/blob/development/NeuroML2CoreTypes/Channels.xml#L492
setting those results in correct simulation (jlems), but nml2 files are invalid according to the schema.

**Comment by pgleeson** [comment]
Added check for `<q10ConductanceScaling>` [here](https://github.com/NeuroML/NeuroML2/blob/development/Schemas/NeuroML2/NeuroML_v2beta4.xsd#L552)
