### ISSUE TITLE
Rename tauSyn to tau in alphaCurrentSynapse

### ISSUE THREAD

**Issue by pgleeson** [NeuroML/NeuroML2#68]
@borismarin I'm creating a cond based alphaSynapse similar to alphaCurrentSynapse. Any reason to have the extra 'Syn' in the attribute name tauSyn?

**Comment by borismarin** [comment]
What's in a name? That which we call a rose
By any other name would smell as sweet.

On 7 January 2016 at 15:05, Padraig Gleeson <notifications@github.com>
wrote:
>
> @borismarin I'm creating a cond based alphaSynapse similar to
alphaCurrentSynapse. Any reason to have the extra 'Syn' in the attribute
name tauSyn?

**Comment by pgleeson** [comment]
Indeed...

I'll make the change here in the schema/comp types/example and leave it up to you to update the Brunel code...

**Comment by tarelli** [comment]
@borismarin che dolce Giulietta

**Comment by pgleeson** [comment]
Done in development https://github.com/NeuroML/NeuroML2/blob/c81c5b6a4d954578f16c5d0b8d52f0720c758033/Schemas/NeuroML2/NeuroML_v2beta4.xsd#L931
