### ISSUE TITLE
We should have children instead of child for some components

### ISSUE THREAD

**Issue by adrianq** [NeuroML/NeuroML2#82]
- [x] property in annotation
- [x] annotation, property, notes under most CompTypes

See #81

cc @borismarin

**Comment by pgleeson** [comment]
annotation and notes should occur only one. But there can certainly be more then one property

**Comment by pgleeson** [comment]
Fixed & consolidated in https://github.com/NeuroML/NeuroML2/commit/8e79a44da6c5ae6aff91a77fb22834f6d70b4fd6
