### ISSUE TITLE
Old and new format for connections

### ISSUE THREAD

**Issue by tarelli** [NeuroML/NeuroML2#89]
Is the old format meant to be deprecated? In Traub for instance some connections use the new format (preCell, see the electrical ones) and some others use the old one (preCellId) . Having support for both means making the code harder to maintain (when looking at the model from the LEMS data model for instance we have to directly confront these strings to access the attributes), in general decisions like "both are valid" should not be taken lightly because then they spread through all the codebases.

![screen shot 2016-06-14 at 12 12 13](https://cloud.githubusercontent.com/assets/81127/16040874/54a90a2c-322a-11e6-80a8-2fbf7b75a9e8.png)

**Comment by pgleeson** [comment]
To be addressed in #90
